[project]
name = "yolo-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy==1.26.4",
    "opencv-python-headless>=4.8.0.74",
    "ultralytics>=8.3.0,<8.4.0",
]
